name: fake_shop
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  lottie: ^1.4.2

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
  - assets/logos/
  - assets/images/
  - assets/lotties/
  fonts:
    - family: Myriad
      fonts:
        - asset: assets/fonts/Myriad-Pro-Regular.ttf
